### ISSUE TITLE
Offer browser pre-bundled version

### ISSUE THREAD

**Issue by photopea** [eugeneware/jpeg-js#48]
Hi guys, could you make this library work in a browser environment? I think Node.js dependencies should be easy to get rid of.

Then, you could make an online demo, so we could compare your library e.g. with this:  http://godromo.com/petitojpeg

**Comment by patrickhulce** [comment]
@photopea this library should already work in a browser environment with something like browserify/webpack. Are there particular node.js dependencies you're struggling with?

**Comment by photopea** [comment]
Hi, I never used browserify or webpack. I think you can write a library, that works with in a browser "as is". Also, could you make live the demo? It should not take too much time.

**Comment by patrickhulce** [comment]
It wouldn't be *crazy* to offer a browser-specific version, but it would be a bad idea to use it. You can do everything this library does using canvas instead without having a 50KB+ dependency. A browser bundled version is not a focus of the project and will not receive first-class support.

If someone is very interested in this though and wants to help out, adding a rollup build pipeline and pointing folks to unpkg with a disclaimer would be cool :)

**Comment by photopea** [comment]
I am not asking to make a browser-specific version. I am asking to make a more general (less specific) version, which works in every JS environment.

Do you thing you could ever go beyond the original as3corelib implementation and improve this library even more? Or you just plan to maintain the exact port of as3 version?

The main reason I want to avoid Canvas JPG compression is, that I would like to add some specific metadata, or to offer even better size/quality ratio, than the browser compressor.

**Comment by patrickhulce** [comment]
This package is distributed over NPM with CommonJS exports. Asking for something that works in a browser "as-is" without any bundler is asking for a browser-specific version. The code itself is already node agnostic with the use of the `useTArray` option except for a single `Buffer` reference in encoder which is easily polyfillable (and in fact is automatically polyfilled by some bundlers). Are you just asking for a workaround for this Buffer reference? This is why I ask what you're having trouble with using in a browser.

> Do you thing you could ever go beyond the original as3corelib implementation and improve this library even more?

This is very much in maintenance mode right now. If someone (maybe you? nice image editor you've got! 😃) wants to step up and add lots of awesome features, great!

> The main reason I want to avoid Canvas JPG compression is, that I would like to add some specific metadata, or to offer even better size/quality ratio, than the browser compressor.

You'll likely be disappointed by this library then. The encoder is measurably worse than libjpegturbo built-in to Chrome, and there's no real metadata support (weak support for EXIF injection in #47).

**Comment by metabench** [comment]
I agree with the idea that making the functionality work using pure JavaScript by default makes the most sense. I've been doing my own work on encoding and decoding, and am now using a UInt8Array as the default binary format. Node's buffer is built on top of an 8 bit JS typed array anyway, so if it works with normal JS Typed Arrays it's very easy to get it working with Node Buffers, easier than the other way round.

I'm interested in adding lots of good features to jpeg-js, and could do with some help of other programmers here too. I am working on a separate codebase right now, and plan to upload it as open-source on Github (and npm) once it's further along. @patrickhulce What do you think of supporting my efforts working on another codebase where some different implementations of parts of jpeg-js will be made and compared against jpeg-js? Right now I'm incorporating some code from jpeg-js into it, and plan on making it work in a more event-driven way (supporting streams), as well as re-implementing and adding some functionality. One example of part of what I plan is to re-implement the Huffman Tree/Table using some lower level optimizations where they work well (likely using a Huffman_Tree class along the way).

There are a variety of things that I'm planning that don't have so much to do with what I understand jpeg-js's goals are, such as non-js (WASM, C++ and GPU acceleration) versions of the same algorithms, and algorithms such as convolutions. Programmers here may be interested in helping to get these things working and interested in using it. Parts of the project, in fact parts that I'm working on right now, will be useful to jpeg-js should I and those who help manage to make improved algorithms / objects that can be put into jpeg-js and can be shown to be an improvement (eg features, passing test coverage, performance improvements, smaller code size).

If anyone here wants to get more into JPEG and codec programming, working on my JavaScript JPEG codec would be a good learning experience too. With jpeg-js being in maintenance mode, separate efforts (which it would be great to be able to talk about and coordinate here within jpeg-js discussions when the subjects come up) could come up with components (ie improved encode and decode functions) that fit easily into jpeg-js.

If anyone wants to get working on this, please let me know and I'll share the code with you ASAP. I plan on making an improved JPEG codec in JS, and it will be worth coordinating improvements that can go into jpeg-js.

**Comment by metabench** [comment]
@patrickhulce I disagree with your comments about the JS-only version being the same as asking for browser-only. I see it as a side issue. They are indeed very similar, but I support making jpeg-js work in any modern JS environment / in the browser.

I also think of the Typed Arrays as being required JS functionality, and am not interested into putting effort into ways not to support Typed Arrays. I'm not here to tell you how to run your project though, I appreciate the code and find it useful. I have different ideas on where to take an improved JPEG JS library, want to work on it, and think that there should be a level of cooperation and coordination between our projects.

**Comment by metabench** [comment]
@photopea Are you interested in working with me to develop improved JPEG processing in JavaScript?My codebase won't assume it's operating in a node.js environment. Whether or not the issue gets solved in jpeg-js is up to the management of this project.

**Comment by patrickhulce** [comment]
I don't even know where to start 😆

I am so confused why you both think this project is not JS-only. I've asked multiple times what specifically you'd like us to do differently without straight answers. (is it literally just #36? we can do that no problem, but that's not a very user-friendly browser API)

The encoder and decoder are 100% JS with 0 node require dependencies, it is simply packaged and distributed as a commonjs module because that is what is most easily consumed by a majority of our users. It is trivially used in the browser using any modern bundler and with `useTArray` could even remove a `Buffer` polyfill. If you're asking for a drop-in browser-ready file that exports the methods to `window` instead of using commonjs modules, I already said we'd be open to that and would welcome the contribution.

FWIW @metabench, downvoting every comment by the maintainers isn't the best way to win support for handing the project over 😉as you can probably tell, there is very little activity here, and with over 1M weekly downloads the name of the game is stability. If your plan is to significantly depart from the existing functionality and API found here, it'd probably be best to just create a new library. If there are places were you find bugs in this implementation, jpeg-js users would obviously welcome any issues and/or PRs you're kind enough to offer :)

**Comment by photopea** [comment]
@photopea just a side comment - I am developing a web-based photo editor www.Photopea.com , which is used by 100 000 people a day, and working with JPGs is an essential task. Photopea can even detect depth-maps or MP4 videos, which may be stored inside a JPG file.

Currently, I use a JPG decoder form pdf.js for JPG decoding. I use Canvas.toDataURL() for JPG encoding (at the end, you have to convert a base64 string to Uint8Array). I can still rewrite metadata in such files (in particular, Photopea opens and stores the DPI information of JPGs and all other formats).

I don't know what you mean by "WASM, C++, GPU acceleration and convolutions". I can't see any way JPG decoding or encoding could be parallelized (for the GPU), or how to use convolutions in that process. You probably mean editing graphics (pixels). But I think such editing operations should not be a part of a JPG encoder/decoder library.

Even though I think the code should be written with as few dependencies as possible, I do not need this library anymore, so I will close the issue.

**Comment by metabench** [comment]
@patrickhulce Sorry for so much downvoting. Maybe I disagreed for wrong reasons too, as I thought jpeg-js required Buffer but if that's not the case then my criticism is misplaced.

I agree that stability of jpeg-js is important. It's possible I'll have some PRs that will solve some issues in jpeg-js.

**Comment by metabench** [comment]
@photopea The reset markers in JPEG files allow parallel decoding. WASM could be used, both in the browser and node, because it would run faster. I agree that convolutions are separate from JPEG processing but I would likely use some similar programming (or some of the same underlying functions / objects) to do both.

I'm also interested in seeing how well JPEG encoding and decoding works on GPUs, particularly if there are small kernels that will enable some of the functions needed to decode JPEG images to be carried out very quickly, or carried out at all and I'll see where the speed limitations are.

I also think there are possibilities for using GPUs for accelerating the search for optimized Huffman tables, but I am not sure about this. At present, jpeg-js uses standard Huffman tables as far as I know.

**Comment by metabench** [comment]
@patrickhulce My personal view about what makes code pure JS only is not having any reference to `Buffer`, but I see that this codebase makes use of that object optional.

Going back into history, `Buffer` existed and was fast before Typed Arrays were standard and integrated into V8. Since then, `Buffer` has been reimplemented within node.js with a Typed Array as its superclass. It's for that reason that I think that use of `Buffer` is no longer useful. Other parts of the code rely on Typed Arrays, so it's not as though jpeg-js would work without Typed Arrays.

Possibly this is pedantic and an unimportant issue but I'm doing my best to give an answer to why (to an extent) I 'think this project is not JS-only'.
