### ISSUE TITLE
DecodeBlock: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by Dewep** [eugeneware/jpeg-js#56]
Hello,

I'm using jimp, which use your library. I have a problem with some images, which, when I want to preview them with jimp, throw a JS error:

```
TypeError: Cannot read property '0' of undefined
    at decodeBlock (XXXXXXXXXXX\node_modules\jpeg-js\lib\decoder.js:264:51)
    at decodeScan (XXXXXXXXXXX\node_modules\jpeg-js\lib\decoder.js:298:11)
    at constructor.parse (XXXXXXXXXXX\node_modules\jpeg-js\lib\decoder.js:744:29)
    at Object.decode [as image/jpeg] (XXXXXXXXXXX\node_modules\jpeg-js\lib\decoder.js:1004:11)
    at Jimp.parseBitmap (XXXXXXXXXXX\node_modules\@jimp\core\dist\utils\image-bitmap.js:115:53)
    at Jimp.parseBitmap (XXXXXXXXXXX\node_modules\@jimp\core\dist\index.js:521:32)
    at new Jimp (XXXXXXXXXXX\node_modules\@jimp\core\dist\index.js:474:13)
    at _construct (XXXXXXXXXXX\node_modules\@babel\runtime\helpers\construct.js:30:21)
    at XXXXXXXXXXX\node_modules\@jimp\core\dist\index.js:1016:32
    at new Promise (<anonymous>)
    at Function.Jimp.read (XXXXXXXXXXX\node_modules\@jimp\core\dist\index.js:1015:10)
    ...
```

I'm pretty sure this is due to the fact that the image must have an invalid format, but it is nevertheless read by all the readers I've tested (Chrome, Paint, Photoshop, Windows Photos, ...).

And after trying to update your lib, so as not to call the function if the value is undefined, it works perfectly (my preview is generated by jimp):

```js
function decodeBlock(component, decode, mcu) {
  var blockRow = (mcu / component.blocksPerLine) | 0;
  var blockCol = mcu % component.blocksPerLine;
  if (component.blocks[blockRow] !== undefined) {
    decode(component, component.blocks[blockRow][blockCol]);
  }
}
```

I'm doing this issue rather than a PR because I don't know anything about the JPEG format, and I don't know if it can have unintended consequences. What do you think about that? Is it possible to fix it? If my `if` is enough, I can of course do the PR to help you.

_I would have appreciated being able to share these images to show you an example of the issue, but these images are private. And if I edit them to remove the private parts, the problem disappears..._

**Comment by patrickhulce** [comment]
Thanks for filing @Dewep! My opinion here is that we should support buggy JPEGs like this as most other readers do, but under some sort of `tolerantDecoding: true` option in order to 

A) help track all the places in the codebase that deviate from normal JPEG behavior
B) help prevent any unintended consequences from creeping into valid JPEGs as much as possible

In this case, it should be completely safe for a JPEG that is otherwise valid, a valid JPEG will never have a missing block like this. If a block is missing, there's really not much we can do other than fail, so skipping with your if is a reasonable alternative. 👍 PR would be great though we should try to artificially construct a file that has this issue if you're unable to share any of those naturally occurring broken images (is the process by which you got them repeatable with a public image perhaps?)

**Comment by Dewep** [comment]
Thank you for your quick answer!

Adding a new option makes perfect sense to me. I just created a PR that adds this option, and checks this undefined value: #57 

Can you take a look on it, please?

Unfortunately I don't have any images to share, and they're not my images either, I don't know how they were created.
